version: 2

sphinx:
  configuration: documentation/source/conf.py
  fail_on_warning: false

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: documentation/requirements.txt

